# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  MEM_CACHE_STORE: "memcached:11211"
  REDIS_URL: "redis://redis:6379/0"
production:
  REDIS_URL: "redis://:p80d046205241fb5352b10b5a9e0af59887cc37881de7dcaf03bcd41f43ef4f7e@ec2-63-32-141-64.eu-west-1.compute.amazonaws.com:26259"